### ISSUE TITLE
Error i18n/core_ext/hash

### ISSUE THREAD

**Issue by gordienko** [conradwt/cassandra-example-using-ruby#95]
When running rails cequel:keyspace:create from the terminal, I get the error LoadError: cannot load such file -- i18n/core_ext/hash

ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21]
Rails 6.1.7

**Comment by conradwt** [comment]
@gordienko Let me investigate and I'll get back to you.

**Comment by conradwt** [comment]
@gordienko Please run the following command within your project root:

```zsh
bundle add i18n -v "= 1.8.11"
```

There appear to be issues with `i18n` version >= `1.9.0`.

**Comment by gordienko** [comment]
@conradwt Added to Gemfile

```
gem 'i18n', '= 1.8.11'
```

Run the command

```
bundle update i18n
```

Now when running `rails cequel:migrate` I got a different error:

```
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
rails aborted!
ArgumentError: Delegation needs a target. Supply a keyword argument 'to' (e.g. delegate :hello, to: :greeter).
/Users/alx/RubymineProjects/cassandra-example-using-ruby/app/models/post.rb:2:in `include'
/Users/alx/RubymineProjects/cassandra-example-using-ruby/app/models/post.rb:2:in `<class:Post>'
/Users/alx/RubymineProjects/cassandra-example-using-ruby/app/models/post.rb:1:in `<main>'
Tasks: TOP => cequel:migrate
(See full trace by running task with --trace)

```

**Comment by gordienko** [comment]
@conradwt, it looks like this will never work for me.

I found this https://stackoverflow.com/questions/65879563/argumenterror-with-cequel-and-ruby3-rails-6.

**Comment by conradwt** [comment]
@gordienko Yes, I will have to redo these projects because Cequel doesn't support Rails 6 and 7 at this time.

**Comment by gordienko** [comment]
@conradwt, Thank you!

**Comment by conradwt** [comment]
@gordienko I was able to downgrade this application to Rails 5.2.8.1 successfully and the steps I've provided work as expected until I can find a Rails 6 and Rails 7 solution.

**Comment by gordienko** [comment]
@conradwt I checked git branch https://github.com/cequel/cequel/issues/430 and it worked for rails 7.
